project_id = "cfdnrbyeuqtrjzzjyuon"

[functions.chat-assistant]
verify_jwt = true

[functions.process-snv-shapefile]
verify_jwt = true

[functions.reset-database]
verify_jwt = false

[functions.send-nc-email]
verify_jwt = false

[functions.send-nc-notification]
verify_jwt = false

[functions.download-vgeo-layer]
verify_jwt = false

[functions.upload-placa-svg]
verify_jwt = true
