project_id = "cfdnrbyeuqtrjzzjyuon"

[functions.reset-database]
verify_jwt = false

[functions.send-nc-email]
verify_jwt = false

[functions.send-nc-notification]
verify_jwt = false

[functions.download-vgeo-layer]
verify_jwt = false
