project_id = "cfdnrbyeuqtrjzzjyuon"

[functions.chat-assistant]
verify_jwt = true

[functions.process-snv-shapefile]
verify_jwt = true
# timeout = 300  # <- COMENTE ou APAGUE ESTA LINHA

[functions.reset-database]
verify_jwt = false

[functions.send-nc-email]
verify_jwt = false

[functions.send-nc-notification]
verify_jwt = false

[functions.download-vgeo-layer]
verify_jwt = false
# timeout = 120  # <- SE EXISTIR ESSA LINHA, COMENTE/APAGUE

[functions.upload-placa-svg]
verify_jwt = true
