project_id = "zyfusvihowprtwatuvws"

[functions.chat-assistant]
verify_jwt = true

[functions.process-snv-shapefile]
verify_jwt = true
# timeout = 300  # <- COMENTE ou APAGUE ESTA LINHA

[functions.reset-database]
verify_jwt = false

[functions.send-nc-email]
verify_jwt = false

[functions.send-nc-notification]
verify_jwt = false

[functions.download-vgeo-layer]
verify_jwt = false
# timeout = 120  # <- SE EXISTIR ESSA LINHA, COMENTE/APAGUE

[functions.upload-placa-svg]
verify_jwt = true

[functions.create_user]
enabled = true
verify_jwt = true
import_map = "./functions/create_user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_user/*.html" ]
