export const CODIGOS_PLACAS = {
  REGULAMENTACAO: [
    { codigo: "R-1", nome: "Parada obrigatória" },
    { codigo: "R-2", nome: "Dê a preferência" },
    { codigo: "R-3", nome: "Sentido proibido" },
    { codigo: "R-4a", nome: "Proibido virar à esquerda" },
    { codigo: "R-4b", nome: "Proibido virar à direita" },
    { codigo: "R-5a", nome: "Proibido retornar à esquerda" },
    { codigo: "R-5b", nome: "Proibido retornar à direita" },
    { codigo: "R-6a", nome: "Proibido estacionar" },
    { codigo: "R-6b", nome: "Estacionamento regulamentado" },
    { codigo: "R-6c", nome: "Proibido parar e estacionar" },
    { codigo: "R-7", nome: "Proibido ultrapassar" },
    { codigo: "R-8a", nome: "Proibido mudar de faixa da esquerda para a direita" },
    { codigo: "R-8b", nome: "Proibido mudar de faixa da direita para a esquerda" },
    { codigo: "R-9", nome: "Proibido trânsito de caminhões" },
    { codigo: "R-10", nome: "Proibido trânsito de veículos automotores" },
    { codigo: "R-11", nome: "Proibido trânsito de veículos de tração animal" },
    { codigo: "R-12", nome: "Proibido trânsito de bicicletas" },
    { codigo: "R-13", nome: "Proibido trânsito de tratores e máquinas de obras" },
    { codigo: "R-14", nome: "Peso bruto total máximo permitido" },
    { codigo: "R-15", nome: "Altura máxima permitida" },
    { codigo: "R-16", nome: "Largura máxima permitida" },
    { codigo: "R-17", nome: "Peso máximo permitido por eixo" },
    { codigo: "R-18", nome: "Comprimento máximo permitido" },
    { codigo: "R-19", nome: "Velocidade máxima permitida" },
    { codigo: "R-20", nome: "Proibido acionar buzina ou sinal sonoro" },
    { codigo: "R-21", nome: "Alfândega" },
    { codigo: "R-22", nome: "Uso obrigatório de corrente" },
    { codigo: "R-23", nome: "Conserve-se à direita" },
    { codigo: "R-24a", nome: "Sentido de circulação da via/pista" },
    { codigo: "R-24b", nome: "Passagem obrigatória" },
    { codigo: "R-25a", nome: "Vire à esquerda" },
    { codigo: "R-25b", nome: "Vire à direita" },
    { codigo: "R-25c", nome: "Siga em frente ou à esquerda" },
    { codigo: "R-25d", nome: "Siga em frente ou à direita" },
    { codigo: "R-26", nome: "Siga em frente" },
    { codigo: "R-27", nome: "Ônibus, caminhões e veículos de grande porte mantenham-se à direita" },
    { codigo: "R-28", nome: "Duplo sentido de circulação" },
    { codigo: "R-29", nome: "Proibido trânsito de pedestres" },
    { codigo: "R-30", nome: "Pedestre, ande pela esquerda" },
    { codigo: "R-31", nome: "Pedestre, ande pela direita" },
    { codigo: "R-32", nome: "Circulação exclusiva de ônibus" },
    { codigo: "R-33", nome: "Sentido de circulação na rotatória" },
    { codigo: "R-34", nome: "Circulação exclusiva de bicicletas" },
    { codigo: "R-35a", nome: "Ciclista, transite à esquerda" },
    { codigo: "R-35b", nome: "Ciclista, transite à direita" },
    { codigo: "R-36a", nome: "Ciclistas à esquerda, pedestres à direita" },
    { codigo: "R-36b", nome: "Pedestres à esquerda, ciclistas à direita" },
    { codigo: "R-37", nome: "Proibido trânsito de motocicletas, motonetas e ciclomotores" },
    { codigo: "R-38", nome: "Proibido trânsito de ônibus" },
    { codigo: "R-39", nome: "Circulação exclusiva de caminhão" },
    { codigo: "R-40", nome: "Trânsito proibido a carros de mão" },
  ],
  ADVERTENCIA: [
    { codigo: "A-1a", nome: "Curva acentuada à esquerda" },
    { codigo: "A-1b", nome: "Curva acentuada à direita" },
    { codigo: "A-2a", nome: "Curva à esquerda" },
    { codigo: "A-2b", nome: "Curva à direita" },
    { codigo: "A-3a", nome: "Pista sinuosa à esquerda" },
    { codigo: "A-3b", nome: "Pista sinuosa à direita" },
    { codigo: "A-4a", nome: "Curva acentuada em 'S' à esquerda" },
    { codigo: "A-4b", nome: "Curva acentuada em 'S' à direita" },
    { codigo: "A-5a", nome: "Curva em 'S' à esquerda" },
    { codigo: "A-5b", nome: "Curva em 'S' à direita" },
    { codigo: "A-6", nome: "Cruzamento de vias" },
    { codigo: "A-7a", nome: "Via lateral à esquerda" },
    { codigo: "A-7b", nome: "Via lateral à direita" },
    { codigo: "A-8", nome: "Interseção em 'T'" },
    { codigo: "A-9", nome: "Bifurcação em 'Y'" },
    { codigo: "A-10a", nome: "Entroncamento oblíquo à esquerda" },
    { codigo: "A-10b", nome: "Entroncamento oblíquo à direita" },
    { codigo: "A-11a", nome: "Junções sucessivas contrárias – primeira à esquerda" },
    { codigo: "A-11b", nome: "Junções sucessivas contrárias – primeira à direita" },
    { codigo: "A-12", nome: "Interseção em círculo" },
    { codigo: "A-13a", nome: "Confluência à esquerda" },
    { codigo: "A-13b", nome: "Confluência à direita" },
    { codigo: "A-14", nome: "Semáforo à frente" },
    { codigo: "A-15", nome: "Parada obrigatória à frente" },
    { codigo: "A-16", nome: "Bonde" },
    { codigo: "A-17", nome: "Pista irregular" },
    { codigo: "A-18", nome: "Saliência ou lombada" },
    { codigo: "A-19", nome: "Depressão" },
    { codigo: "A-20a", nome: "Declive acentuado" },
    { codigo: "A-20b", nome: "Aclive acentuado" },
    { codigo: "A-21a", nome: "Estreitamento de pista ao centro" },
    { codigo: "A-21b", nome: "Estreitamento de pista à esquerda" },
    { codigo: "A-21c", nome: "Estreitamento de pista à direita" },
    { codigo: "A-21d", nome: "Alargamento de pista à esquerda" },
    { codigo: "A-21e", nome: "Alargamento de pista à direita" },
    { codigo: "A-22", nome: "Ponte estreita" },
    { codigo: "A-23", nome: "Ponte móvel" },
    { codigo: "A-24", nome: "Obras" },
    { codigo: "A-25", nome: "Mão dupla adiante" },
    { codigo: "A-26a", nome: "Sentido único" },
    { codigo: "A-26b", nome: "Sentido duplo" },
    { codigo: "A-27", nome: "Área com desmoronamento" },
    { codigo: "A-28", nome: "Pista escorregadia" },
    { codigo: "A-29", nome: "Projeção de cascalho" },
    { codigo: "A-30a", nome: "Trânsito de ciclistas" },
    { codigo: "A-30b", nome: "Passagem sinalizada de ciclistas" },
    { codigo: "A-30c", nome: "Trânsito compartilhado por ciclistas e pedestres" },
    { codigo: "A-31", nome: "Trânsito de tratores ou maquinária agrícola" },
    { codigo: "A-32a", nome: "Trânsito de pedestres" },
    { codigo: "A-32b", nome: "Passagem sinalizada de pedestres" },
    { codigo: "A-33a", nome: "Área escolar" },
    { codigo: "A-33b", nome: "Passagem sinalizada de escolares" },
    { codigo: "A-34", nome: "Crianças" },
    { codigo: "A-35", nome: "Animais" },
    { codigo: "A-36", nome: "Animais selvagens" },
    { codigo: "A-37", nome: "Altura limitada" },
    { codigo: "A-38", nome: "Largura limitada" },
    { codigo: "A-39", nome: "Passagem de nível sem barreira" },
    { codigo: "A-40", nome: "Passagem de nível com barreira" },
    { codigo: "A-41", nome: "Cruz de Santo André" },
    { codigo: "A-42a", nome: "Início de pista dupla" },
    { codigo: "A-42b", nome: "Fim de pista dupla" },
    { codigo: "A-42c", nome: "Pista dividida" },
    { codigo: "A-43", nome: "Aeroporto" },
    { codigo: "A-44", nome: "Vento lateral" },
    { codigo: "A-45", nome: "Rua sem saída" },
    { codigo: "A-46", nome: "Peso bruto total limitado" },
    { codigo: "A-47", nome: "Peso limitado por eixo" },
    { codigo: "A-48", nome: "Comprimento limitado" },
  ],
  INDICACAO: [
    { codigo: "ID-1", nome: "Identificação de rodovia" },
    { codigo: "ID-2", nome: "Identificação de município" },
    { codigo: "ID-3", nome: "Identificação de região" },
    { codigo: "ID-4", nome: "Identificação de obra de arte" },
    { codigo: "ID-5", nome: "Placa de quilometragem" },
    { codigo: "ID-6", nome: "Identificação de divisa" },
    { codigo: "ID-7", nome: "Identificação de pedágio" },
    { codigo: "OD-1", nome: "Placa de pré-sinalização" },
    { codigo: "OD-2", nome: "Placa de confirmação" },
    { codigo: "OD-3", nome: "Placa de distância" },
    { codigo: "ED-1", nome: "Placa educativa" },
    { codigo: "SAU-01", nome: "Estacionamento" },
    { codigo: "SAU-02", nome: "Mecânico" },
    { codigo: "SAU-03", nome: "Hotel" },
    { codigo: "SAU-04", nome: "Restaurante" },
    { codigo: "SAU-05", nome: "Pedágio" },
    { codigo: "SAU-06", nome: "Posto de combustível" },
    { codigo: "SAU-07", nome: "Telefone público" },
    { codigo: "SAU-08", nome: "Pronto-socorro" },
    { codigo: "SAU-09", nome: "Aeroporto" },
    { codigo: "SAU-10", nome: "Porto" },
    { codigo: "SAU-11", nome: "Rodoviária" },
    { codigo: "SAU-12", nome: "Terminal ferroviário" },
    { codigo: "SAU-13", nome: "Área de camping" },
    { codigo: "SAU-14", nome: "Borracheiro" },
    { codigo: "SAU-15", nome: "Polícia rodoviária" },
    { codigo: "SAU-16", nome: "Informações turísticas" },
    { codigo: "SAU-17", nome: "Banheiros" },
    { codigo: "SAU-18", nome: "Mirante" },
    { codigo: "SAU-19", nome: "Centro de compras" },
    { codigo: "SAU-20", nome: "Deficientes físicos" },
    { codigo: "SAU-21", nome: "Área de descanso" },
    { codigo: "SAU-22", nome: "Táxi" },
    { codigo: "SAU-23", nome: "Bombeiros" },
    { codigo: "SAU-24", nome: "Chuveiros" },
    { codigo: "SAU-25", nome: "Salva-vidas" },
    { codigo: "SAU-26", nome: "Lanchonete" },
    { codigo: "TNA-01", nome: "Praia" },
    { codigo: "TNA-02", nome: "Cachoeira" },
    { codigo: "TNA-03", nome: "Patrimônio natural" },
    { codigo: "TNA-04", nome: "Gruta ou caverna" },
    { codigo: "TNA-05", nome: "Montanha" },
    { codigo: "TNA-06", nome: "Rio ou lago" },
    { codigo: "TNA-07", nome: "Floresta" },
    { codigo: "TNA-08", nome: "Parque natural" },
    { codigo: "TNA-09", nome: "Observação de fauna" },
    { codigo: "THC-01", nome: "Museu" },
    { codigo: "THC-02", nome: "Arquitetura religiosa" },
    { codigo: "THC-03", nome: "Centro cultural" },
    { codigo: "THC-04", nome: "Monumento ou estátua" },
    { codigo: "THC-05", nome: "Sítio histórico" },
    { codigo: "THC-06", nome: "Ruínas" },
    { codigo: "THC-07", nome: "Teatro" },
    { codigo: "THC-08", nome: "Biblioteca" },
    { codigo: "THC-09", nome: "Artesanato" },
    { codigo: "THC-10", nome: "Centro histórico" },
    { codigo: "TAD-01", nome: "Aeroclube" },
    { codigo: "TAD-02", nome: "Marina" },
    { codigo: "TAD-03", nome: "Esportes náuticos" },
    { codigo: "TAD-04", nome: "Pesca" },
    { codigo: "TAD-05", nome: "Mergulho" },
    { codigo: "TAD-06", nome: "Golfe" },
    { codigo: "TAD-07", nome: "Hipismo" },
    { codigo: "TAD-08", nome: "Rapel ou escalada" },
    { codigo: "TAD-09", nome: "Asa delta" },
    { codigo: "TAD-10", nome: "Parapente" },
    { codigo: "TAD-11", nome: "Surfe" },
    { codigo: "TAD-12", nome: "Esqui aquático" },
    { codigo: "TAD-13", nome: "Rafting" },
    { codigo: "TAD-14", nome: "Estádio" },
    { codigo: "TAR-01", nome: "Praça" },
    { codigo: "TAR-02", nome: "Barco de passeio" },
    { codigo: "TAR-03", nome: "Parque urbano" },
    { codigo: "TIT-01", nome: "Teatro" },
    { codigo: "TIT-02", nome: "Festas populares" },
    { codigo: "TIT-03", nome: "Zoológico" },
    { codigo: "TIT-04", nome: "Pavilhão de feiras" },
    { codigo: "TIT-05", nome: "Jardim botânico" },
    { codigo: "TIT-06", nome: "Aquário" },
    { codigo: "TIT-07", nome: "Parque temático" },
    { codigo: "TIT-08", nome: "Cassino" },
    { codigo: "TIT-09", nome: "Centro de convenções" },
    { codigo: "TIT-10", nome: "Autódromo" },
    { codigo: "TIT-11", nome: "Parque de diversões" },
  ],
} as const;

// Array combinado para facilitar uso em select/dropdown
export const TODAS_PLACAS = [
  ...CODIGOS_PLACAS.REGULAMENTACAO,
  ...CODIGOS_PLACAS.ADVERTENCIA,
  ...CODIGOS_PLACAS.INDICACAO,
];

export type CodigoPlaca = typeof TODAS_PLACAS[number];
